spring.main.allow-bean-definition-overriding: true
security:
  oauth2:
    client:
      clientId: <Tu cliente ID>
      clientSecret: <Tu secret client>
      accessTokenUri: https://<Tu subdominio>.onelogin.com/oidc/token
      userAuthorizationUri: https://<Tu subdominio>.onelogin.com/oidc/auth
      tokenName: access_token
      authorizedGrantTypes: authorization_code
      authenticationScheme: form
      clientAuthenticationScheme: form
      scope: openid,profile,email
    resource:
      userInfoUri: https://<Tu subdominio>.onelogin.com/oidc/me
server:
  port : 8081
